name: Krypto CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Yarn with cache 🔧
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies 📌
        run: yarn --frozen-lockfile
      - name: Lint Check 🍱
        run: yarn lint
      - name: Run all tests 🤡
        run: yarn test
      - name: Build with Vite ⚡️
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    environment: Production
    env:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
    steps:
      - name: Deploy to Netlify 🚀
        run: echo "Success to deploy to Netlify! Yo $NETLIFY_SITE_ID"


