name: Krypto CI pipeline on PR (Vite)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'workspace/client/**'

jobs:
  vite_build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Yarn with cache 🔧
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies 📌
        run: yarn --frozen-lockfile
      - name: Lint Check 🍱
        run: yarn lint
      - name: Build with Vite ⚡️
        run: yarn client:build
      - name: Run tests on Vite app 🤡
        run: yarn client:test


